// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts
// import * as dotenv from "dotenv";
// import * as path from "path";

import { defineConfig } from "prisma/config";
import dotenv from "dotenv";

dotenv.config();

export default defineConfig({
  migrate: {
    datasource: "db",
    url: process.env.DATABASE_URL,
  },
});
